# Generated by Django 6.0 on 2026-01-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivarity",
            name="description",
            field=models.TextField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="chaivarity",
            name="price",
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
