# Generated by Django 6.0.1 on 2026-01-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=15)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("HR", "HUMAN RESOURCE"),
                            ("PROG", "PROGRAMMER"),
                            ("PR", "PROMOTIONAL"),
                            ("SA", "SALES"),
                        ],
                        max_length=10,
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_of_joining", models.DateField()),
            ],
        ),
    ]
