# Generated by Django 6.0 on 2026-01-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chai", "0002_chaivarity_description_chaivarity_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chaivarity",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
